[tools]
amp = "latest"
fzf = "latest"
github-cli = "latest"
glab = "latest"
go = "latest"
just = "latest"
node = "25"
opencode = "latest"
pre-commit = "latest"
python = "latest"
shellcheck = "latest"
shfmt = "latest"
uv = "latest"
yamlfmt = "latest"
zoxide = "latest"
