[tools]
amp = "latest"
dua = "latest"
fzf = "latest"
github-cli = "latest"
glab = "latest"
go = "latest"
just = "latest"
node = "25"
opencode = "latest"
pipx = "latest"
"pipx:pre-commit" = "latest"
python = "latest"
shellcheck = "latest"
shfmt = "latest"
uv = "latest"
yamlfmt = "latest"
